spring.application.name=langchian4j

gemini.model.name=gemini-3.8-flash
gemini.api.key=your_google_gemini_api_key

# groq.model.name=qwen/qwen3.6-27b
# groq.api.key=your_goq_api_key
# groq.base.url=https://api.groq.com/openai/v1


# langchain4j.http.clientBuilderFactory=dev.langchain4j.http.client.spring.restclient.SpringRestClientBuilderFactory